import { InventoryProduct } from '../types/product';

export const mockInventoryItems: InventoryProduct[] = [
  {
    id: 1,
    name: 'Pommes',
    prix: '125₽',
    quantity: '10',
    unit: 'kg',
    description: 'Pommes fraîches',
  },
  {
    id: 2,
    name: 'Carottes',
    prix: '80₽',
    quantity: '5',
    unit: 'kg',
    description: 'Carottes fraîches',
  },
  {
    id: 3,
    name: 'Pain',
    prix: '960₽',
    quantity: '3',
    unit: 'pièces',
    description: 'Pain frais',
  },
  {
    id: 4,
    name: 'Lait',
    prix: '180₽',
    quantity: '2',
    unit: 'l',
    description: 'Lait entier',
  },
  {
    id: 5,
    name: 'Fromage blanc',
    prix: '320₽',
    quantity: '1.5',
    unit: 'kg',
    description: 'Fromage blanc',
  },
  {
    id: 6,
    name: 'Poulet',
    prix: '450₽',
    quantity: '2.5',
    unit: 'kg',
    description: 'Poulet de volaille',
  },
  {
    id: 7,
    name: 'Tomates',
    prix: '260₽',
    quantity: '3',
    unit: 'kg',
    description: 'Tomates fraîches',
  },
  {
    id: 8,
    name: 'Concombres',
    prix: '180₽',
    quantity: '2',
    unit: 'kg',
    description: 'Concombres frais',
  },
  {
    id: 9,
    name: 'Oeufs',
    prix: '150₽',
    quantity: '30',
    unit: 'pièces',
    description: 'Oeufs frais',
  },
  {
    id: 10,
    name: 'Riz',
    prix: '95₽',
    quantity: '5',
    unit: 'kg',
    description: 'Riz basmati',
  },
  {
    id: 11,
    name: 'Pâtes',
    prix: '120₽',
    quantity: '4',
    unit: 'kg',
    description: 'Pâtes fraîches',
  },
  {
    id: 12,
    name: 'Yaourt',
    prix: '70₽',
    quantity: '12',
    unit: 'pièces',
    description: 'Yaourt nature',
  },
  {
    id: 13,
    name: 'Bœuf',
    prix: '780₽',
    quantity: '1.5',
    unit: 'kg',
    description: 'Bœuf haché',
  },
  {
    id: 14,
    name: 'Saumon',
    prix: '1200₽',
    quantity: '1',
    unit: 'kg',
    description: 'Saumon frais',
  },
  {
    id: 15,
    name: 'Oranges',
    prix: '240₽',
    quantity: '3',
    unit: 'kg',
    description: 'Oranges fraîches',
  },
  {
    id: 16,
    name: 'Bananes',
    prix: '160₽',
    quantity: '2',
    unit: 'kg',
    description: 'Bananes matures',
  },
  {
    id: 17,
    name: 'Champignons',
    prix: '420₽',
    quantity: '1',
    unit: 'kg',
    description: 'Champignons de Paris',
  },
  {
    id: 18,
    name: 'Fraises',
    prix: '350₽',
    quantity: '0.5',
    unit: 'kg',
    description: 'Fraises fraîches',
  },
  {
    id: 19,
    name: 'Miel',
    prix: '550₽',
    quantity: '0.7',
    unit: 'l',
    description: "Miel d'abeille",
  },
  {
    id: 20,
    name: "Huile d'olive",
    prix: '480₽',
    quantity: '1',
    unit: 'l',
    description: "Huile d'olive extra vierge",
  },
  {
    id: 21,
    name: 'Pommes de terre',
    prix: '65₽',
    quantity: '10',
    unit: 'kg',
    description: 'Pommes de terre fraîches',
  },
  {
    id: 22,
    name: 'Crème fraîche',
    prix: '190₽',
    quantity: '0.5',
    unit: 'l',
    description: 'Crème fraîche',
  },
  {
    id: 23,
    name: 'Chocolat',
    prix: '280₽',
    quantity: '0.3',
    unit: 'kg',
    description: 'Chocolat noir',
  },
  {
    id: 24,
    name: 'Thé',
    prix: '320₽',
    quantity: '0.2',
    unit: 'kg',
    description: 'Thé noir',
  },
  {
    id: 25,
    name: 'Café',
    prix: '650₽',
    quantity: '0.5',
    unit: 'kg',
    description: 'Café torréfié',
  },
  {
    id: 26,
    name: 'Avocats',
    prix: '220₽',
    quantity: '4',
    unit: 'pièces',
    description: 'Avocats frais',
  },
  {
    id: 27,
    name: 'Beurre',
    prix: '280₽',
    quantity: '0.5',
    unit: 'kg',
    description: 'Beurre de cacahuète',
  },
  {
    id: 28,
    name: 'Saucisses',
    prix: '380₽',
    quantity: '1',
    unit: 'kg',
    description: 'Saucisses de porc',
  },
  {
    id: 29,
    name: "Jus d'orange",
    prix: '170₽',
    quantity: '2',
    unit: 'l',
    description: "Jus d'orange pressé",
  },
  {
    id: 30,
    name: 'Eau minérale',
    prix: '50₽',
    quantity: '6',
    unit: 'l',
    description: 'Eau minérale naturelle',
  },
  {
    id: 31,
    name: 'Pomelos',
    prix: '290₽',
    quantity: '1.5',
    unit: 'kg',
    description: 'Pomelos frais',
  },
  {
    id: 32,
    name: 'Citrons',
    prix: '280₽',
    quantity: '1',
    unit: 'kg',
    description: 'Citrons frais',
  },
  {
    id: 33,
    name: 'Kiwis',
    prix: '320₽',
    quantity: '1',
    unit: 'kg',
    description: 'Kiwis frais',
  },
  {
    id: 34,
    name: 'Farine',
    prix: '85₽',
    quantity: '2',
    unit: 'kg',
    description: 'Farine de blé',
  },
  {
    id: 35,
    name: 'Sucre',
    prix: '75₽',
    quantity: '3',
    unit: 'kg',
    description: 'Sucre de canne',
  },
  {
    id: 36,
    name: 'Sel',
    prix: '45₽',
    quantity: '1',
    unit: 'kg',
    description: 'Sel de mer',
  },
  {
    id: 37,
    name: 'Yaourt grec',
    prix: '210₽',
    quantity: '0.5',
    unit: 'kg',
    description: 'Yaourt grec',
  },
  {
    id: 38,
    name: 'Pamplemousses',
    prix: '230₽',
    quantity: '2',
    unit: 'kg',
    description: 'Pamplemousses',
  },
  {
    id: 39,
    name: 'Oignons',
    prix: '70₽',
    quantity: '3',
    unit: 'kg',
    description: 'Oignons frais',
  },
  {
    id: 40,
    name: 'Poivrons',
    prix: '320₽',
    quantity: '1',
    unit: 'kg',
    description: 'Poivrons frais',
  },
];
