import { InventoryProduct } from '../types/product';

export const mockInventoryItems: InventoryProduct[] = [
  {
    id: 1,
    name: 'Pommes',
    price: '125₽',
    quantity: '10',
    unitExpression: 'kg',
    description: 'Pommes fraîches',
    minOrder: 1,
  },
  {
    id: 2,
    name: 'Carottes',
    price: '80₽',
    quantity: '5',
    unitExpression: 'kg',
    description: 'Carottes fraîches',
    minOrder: 1,
  },
  {
    id: 3,
    name: 'Pain',
    price: '960₽',
    quantity: '3',
    unitExpression: 'pièces',
    description: 'Pain frais',
    minOrder: 1,
  },
  {
    id: 4,
    name: 'Lait',
    price: '180₽',
    quantity: '2',
    unitExpression: 'l',
    description: 'Lait entier',
    minOrder: 1,
  },
  {
    id: 5,
    name: 'Fromage blanc',
    price: '320₽',
    quantity: '1.5',
    unitExpression: 'kg',
    description: 'Fromage blanc',
    minOrder: 1,
  },
  {
    id: 6,
    name: 'Poulet',
    price: '450₽',
    quantity: '2.5',
    unitExpression: 'kg',
    description: 'Poulet de volaille',
    minOrder: 1,
  },
  {
    id: 7,
    name: 'Tomates',
    price: '260₽',
    quantity: '3',
    unitExpression: 'kg',
    description: 'Tomates fraîches',
    minOrder: 1,
  },
  {
    id: 8,
    name: 'Concombres',
    price: '180₽',
    quantity: '2',
    unitExpression: 'kg',
    description: 'Concombres frais',
    minOrder: 1,
  },
  {
    id: 9,
    name: 'Oeufs',
    price: '150₽',
    quantity: '30',
    unitExpression: 'pièces',
    description: 'Oeufs frais',
    minOrder: 1,
  },
  {
    id: 10,
    name: 'Riz',
    price: '95₽',
    quantity: '5',
    unitExpression: 'kg',
    description: 'Riz basmati',
    minOrder: 1,
  },
  {
    id: 11,
    name: 'Pâtes',
    price: '120₽',
    quantity: '4',
    unitExpression: 'kg',
    description: 'Pâtes fraîches',
    minOrder: 1,
  },
  {
    id: 12,
    name: 'Yaourt',
    price: '70₽',
    quantity: '12',
    unitExpression: 'pièces',
    description: 'Yaourt nature',
    minOrder: 1,
  },
  {
    id: 13,
    name: 'Bœuf',
    price: '780₽',
    quantity: '1.5',
    unitExpression: 'kg',
    description: 'Bœuf haché',
    minOrder: 1,
  },
  {
    id: 14,
    name: 'Saumon',
    price: '1200₽',
    quantity: '1',
    unitExpression: 'kg',
    description: 'Saumon frais',
    minOrder: 1,
  },
  {
    id: 15,
    name: 'Oranges',
    price: '240₽',
    quantity: '3',
    unitExpression: 'kg',
    description: 'Oranges fraîches',
    minOrder: 1,
  },
  {
    id: 16,
    name: 'Bananes',
    price: '160₽',
    quantity: '2',
    unitExpression: 'kg',
    description: 'Bananes matures',
    minOrder: 1,
  },
  {
    id: 17,
    name: 'Champignons',
    price: '420₽',
    quantity: '1',
    unitExpression: 'kg',
    description: 'Champignons de Paris',
    minOrder: 1,
  },
  {
    id: 18,
    name: 'Fraises',
    price: '350₽',
    quantity: '0.5',
    unitExpression: 'kg',
    description: 'Fraises fraîches',
    minOrder: 1,
  },
  {
    id: 19,
    name: 'Miel',
    price: '550₽',
    quantity: '0.7',
    unitExpression: 'l',
    description: "Miel d'abeille",
    minOrder: 1,
  },
  {
    id: 20,
    name: "Huile d'olive",
    price: '480₽',
    quantity: '1',
    unitExpression: 'l',
    description: "Huile d'olive extra vierge",
    minOrder: 1,
  },
  {
    id: 21,
    name: 'Pommes de terre',
    price: '65₽',
    quantity: '10',
    unitExpression: 'kg',
    description: 'Pommes de terre fraîches',
    minOrder: 1,
  },
  {
    id: 22,
    name: 'Crème fraîche',
    price: '190₽',
    quantity: '0.5',
    unitExpression: 'l',
    description: 'Crème fraîche',
    minOrder: 1,
  },
  {
    id: 23,
    name: 'Chocolat',
    price: '280₽',
    quantity: '0.3',
    unitExpression: 'kg',
    description: 'Chocolat noir',
    minOrder: 1,
  },
  {
    id: 24,
    name: 'Thé',
    price: '320₽',
    quantity: '0.2',
    unitExpression: 'kg',
    description: 'Thé noir',
    minOrder: 1,
  },
  {
    id: 25,
    name: 'Café',
    price: '650₽',
    quantity: '0.5',
    unitExpression: 'kg',
    description: 'Café torréfié',
    minOrder: 1,
  },
  {
    id: 26,
    name: 'Avocats',
    price: '220₽',
    quantity: '4',
    unitExpression: 'pièces',
    description: 'Avocats frais',
    minOrder: 1,
  },
  {
    id: 27,
    name: 'Beurre',
    price: '280₽',
    quantity: '0.5',
    unitExpression: 'kg',
    description: 'Beurre de cacahuète',
    minOrder: 1,
  },
  {
    id: 28,
    name: 'Saucisses',
    price: '380₽',
    quantity: '1',
    unitExpression: 'kg',
    description: 'Saucisses de porc',
    minOrder: 1,
  },
  {
    id: 29,
    name: "Jus d'orange",
    price: '170₽',
    quantity: '2',
    unitExpression: 'l',
    description: "Jus d'orange pressé",
    minOrder: 1,
  },
  {
    id: 30,
    name: 'Eau minérale',
    price: '50₽',
    quantity: '6',
    unitExpression: 'l',
    description: 'Eau minérale naturelle',
    minOrder: 1,
  },
  {
    id: 31,
    name: 'Pomelos',
    price: '290₽',
    quantity: '1.5',
    unitExpression: 'kg',
    description: 'Pomelos frais',
    minOrder: 1,
  },
  {
    id: 32,
    name: 'Citrons',
    price: '280₽',
    quantity: '1',
    unitExpression: 'kg',
    description: 'Citrons frais',
    minOrder: 1,
  },
  {
    id: 33,
    name: 'Kiwis',
    price: '320₽',
    quantity: '1',
    unitExpression: 'kg',
    description: 'Kiwis frais',
    minOrder: 1,
  },
  {
    id: 34,
    name: 'Farine',
    price: '85₽',
    quantity: '2',
    unitExpression: 'kg',
    description: 'Farine de blé',
    minOrder: 1,
  },
  {
    id: 35,
    name: 'Sucre',
    price: '75₽',
    quantity: '3',
    unitExpression: 'kg',
    description: 'Sucre de canne',
    minOrder: 1,
  },
  {
    id: 36,
    name: 'Sel',
    price: '45₽',
    quantity: '1',
    unitExpression: 'kg',
    description: 'Sel de mer',
    minOrder: 1,
  },
  {
    id: 37,
    name: 'Yaourt grec',
    price: '210₽',
    quantity: '0.5',
    unitExpression: 'kg',
    description: 'Yaourt grec',
    minOrder: 1,
  },
  {
    id: 38,
    name: 'Pamplemousses',
    price: '230₽',
    quantity: '2',
    unitExpression: 'kg',
    description: 'Pamplemousses',
    minOrder: 1,
  },
  {
    id: 39,
    name: 'Oignons',
    price: '70₽',
    quantity: '3',
    unitExpression: 'kg',
    description: 'Oignons frais',
    minOrder: 1,
  },
  {
    id: 40,
    name: 'Poivrons',
    price: '320₽',
    quantity: '1',
    unitExpression: 'kg',
    description: 'Poivrons frais',
    minOrder: 1,
  },
];
